# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_signalitemtype_code')],
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='watchdog.signal')),
                ('signal_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.signalitemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.signalitemtype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "watchdog_signalevent" ("content_type_id", "id", "metadata", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_at", "signal_type_id") VALUES (NEW."content_type_id", NEW."id", NEW."metadata", NEW."object_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."processed_at", NEW."signal_type_id"); RETURN NULL;', hash='e9a03cc00f29d1ad014ebc5e23a00d7d411692f0', operation='INSERT', pgid='pgtrigger_insert_insert_57bc9', table='watchdog_signal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "watchdog_signalevent" ("content_type_id", "id", "metadata", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_at", "signal_type_id") VALUES (NEW."content_type_id", NEW."id", NEW."metadata", NEW."object_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."processed_at", NEW."signal_type_id"); RETURN NULL;', hash='910fc68ddc004fd9193a6fc68439787a58769519', operation='UPDATE', pgid='pgtrigger_update_update_0f2e0', table='watchdog_signal', when='AFTER')),
        ),
    ]
