# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iam', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolefieldpermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='userfieldpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userfieldpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rolefieldpermission',
            constraint=models.UniqueConstraint(fields=('role', 'content_type', 'field_name'), name='iam_rolefieldpermission_unique'),
        ),
        migrations.AddConstraint(
            model_name='userfieldpermission',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'field_name'), name='iam_userfieldpermission_unique'),
        ),
    ]
