# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFieldLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(help_text="Django ORM path, e.g. 'person__name'", max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, help_text='Optional grouping for UI sections', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'field_path')},
            },
        ),
    ]
