# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('storedquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='storedquery.savedquery'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationrule'),
        ),
        migrations.AddField(
            model_name='automationactionrun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_runs', to='automation.automationrun'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='automation.automationrule'),
        ),
    ]
