# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0002_initial'),
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtrigger',
            name='signal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchdog.signalitemtype'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationtrigger'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='automation.automationtrigger'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'signal_type'], name='automation__trigger_ab5743_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'schedule'], name='automation__trigger_623838_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationtrigger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schedule__isnull', True), ('signal_type__isnull', False), ('trigger_type', 'S')), models.Q(('schedule__isnull', False), ('signal_type__isnull', True), ('trigger_type', 'T')), _connector='OR'), name='automation_automationtrigger_valid_trigger_configuration'),
        ),
        migrations.AddConstraint(
            model_name='automationtrigger',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='automation_automationtrigger_unique_non_null_name'),
        ),
    ]
