# Generated by Django 6.0.7 on 2026-08-28 20:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='formtype_name_not_empty'), models.UniqueConstraint(fields=('code', 'version'), name='unique_formtype_code_version')],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('D', 'Date'), ('DR', 'Date Range'), ('E', 'Enum'), ('S', 'Dynamic Select'), ('DT', 'DateTime'), ('DTR', 'DateTime Range')], max_length=3)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dynamicforms.formtype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted'), ('L', 'Locked')], default='D', max_length=1)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicforms.formtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dynamicforms.forminstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicforms.formquestion')),
            ],
            options={
                'unique_together': {('form_instance', 'question')},
            },
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form_type', 'label'), name='unique_question_label_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form_type', 'order'), name='unique_question_order_per_form'),
        ),
    ]
