# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('storedquery', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedqueryevent',
            name='model',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='savedqueryevent',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedqueryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='savedqueryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='storedquery.savedquery'),
        ),
        migrations.AddField(
            model_name='savedquerypermission',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='storedquery.savedquery'),
        ),
        migrations.AddField(
            model_name='savedquerypermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='savedquerypermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedquery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), ('is_system', False), _connector='OR'), name='system_queries_have_no_owner'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='savedquery',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "storedquery_savedqueryevent" ("created_at", "description", "id", "is_system", "model_id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_system", NEW."model_id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."query", NEW."updated_at"); RETURN NULL;', hash='5ef4529343f3f5d05051f1a17fa61ebdc38d9d6e', operation='INSERT', pgid='pgtrigger_insert_insert_96b87', table='storedquery_savedquery', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='savedquery',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "storedquery_savedqueryevent" ("created_at", "description", "id", "is_system", "model_id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_system", NEW."model_id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."query", NEW."updated_at"); RETURN NULL;', hash='0c6507d8b27b87b72ff8d947eecf642ccf0633d0', operation='UPDATE', pgid='pgtrigger_update_update_0d047', table='storedquery_savedquery', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='savedquerypermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='query_permission_role_xor_user'),
        ),
        migrations.AddConstraint(
            model_name='savedquerypermission',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('query', 'role'), name='unique_query_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='savedquerypermission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('query', 'user'), name='unique_query_user_permission'),
        ),
    ]
